# Instructions for GitHub to build Dusk's smart contract compilers.

on:
  pull_request:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master

name: Dusk Contract Compilers

jobs:
  target:
    strategy:
      matrix:
        target: [
          aarch64-apple-darwin,
        ]
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y ninja-build

      - name: Setup dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install ninja gettext &&
          brew link --force gettext &&
          brew install llvm &&
          echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc
  
      - name: Generate configuration
        run: |
          HOST=${{ matrix.target }} envsubst < config.template.toml > config.toml &&
          echo "OS version: $(uname -v)"
          cat config.toml

      - name: Run build
        run: |
          git config --local --get-regex "remote\..*\.url"
          git remote add upstream https://github.com/rust-lang/rust
          echo "This is the number of commits in the repo: $(git rev-list --count HEAD)"
          ./x.py dist

      - name: Set artifact name
        id: artifact-name
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "name=duskc-${{ matrix.target }}-${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "name=duskc-${{ matrix.target }}-${{ github.sha }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: build/dist/
